export const BITS_IN_MEGABIT = 1_000_000;
export const BYTES_IN_MEGABYTE = 1024 * 1024;
export const UPLOAD_SIZE_MB = 5; // Simulated upload size
export const DOWNLOAD_FILE_URL = `/download-test.bin`;
export const PING_FILE_URL = `/favicon.ico`; // Small file for ping test
export const MAX_HISTORY_POINTS_PER_STAGE = 60;
export const MIN_MEASUREMENT_DURATION_SEC = 0.1;
export const PING_TIMEOUT_MS = 3500;
export const DOWNLOAD_UPDATE_INTERVAL_MS = 150;
export const UPLOAD_UPDATE_INTERVAL_MS = 150;
export const NUM_PINGS = 4;
